### ISSUE TITLE
A little confused as to why the elements that were peeked or dequeued are getting deleted.

### ISSUE THREAD

**Issue by dorothysyu** [BryceCubes/Assignment-1-Part-2#9]
I know @steven-horn said this:

> Every time you dequeue or peek an element, you must also delete that element or else there will be a memory leak. For example, in test1 at line 24, you do q->peek()->equals(o). Instead, you must do String* s = q->peek(), then check that s->equals(o), then delete s. This must happen everywhere that you peek or dequeue.

But from what I've been seeing behavior-wise, s shouldn't be deleted. Deleting s would destroy whatever it's pointing to (object o), which means that you cannot access that object anymore. Whatever element is returned by dequeue after you delete s will be null.

I looked it up and [I think this confirmed it](https://stackoverflow.com/questions/40134139/c-delete-a-pointer-free-memory/40134240). `String* s = q->peek()` and `String* st = q->dequeue` don't use the `new` keyword (unless I am implementing this wrong), so delete is unnecessary here. 

Let me know what you think.

**Comment by ZhichaoC** [comment]
Ah, I have missed that comment (because I was having class at that time). You are right, the spec did not mention whether to make a copy of the object then push into the queue or push the reference directly into the queue, therefore, the test should not cover that. This is leave for the implementation. I will change the tests accordingly. Sorry if that cause any inconvenience.

**Comment by dorothysyu** [comment]
No worries, thank you!

**Comment by ZhichaoC** [comment]
Updated. If you have more questions, please feel free to ask.

**Comment by sbhornjr** [comment]
Just want to add, the way that we implemented the Queue is that the Queue has full ownership of its own elements and nothing else. We think this is a common and well-designed choice, and one that was discussed in class. 

So, when we enqueue, we create a copy of the String (or Object) and store that. If the String is deleted somewhere else now, the Queue still has it. So, when we dequeue and peek, we get back a copy of the original element rather than the exact one. So, the copy just be deleted along with the original.

So, yes, this is an implementation choice and can be done either way. We will add delete statements in our version of your tests to avoid memory leaks.
